# Generated by Django 5.2.7 on 2025-10-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='writer',
            new_name='user',
        ),
    ]
